---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install general dependencies for Caffe
  apt: name={{ item }} state=present update_cache=yes
  with_items: pkg_requirements
  when: ansible_os_family == 'Debian'

- name: Install linux kernel
  apt: name={{ item }} state=present
  with_items: linux_kernel_pkgs

- name: Check CUDA repository package installed
  command: dpkg-query -W cuda-repo-ubuntu1404
  register: cuda_repo_check_deb
  changed_when: cuda_repo_check_deb.rc == 1
  ignore_errors: yes

- name: Download CUDA repository package
  get_url:
    url="{{ cuda_repo_pkg_url }}"
    dest="{{ pkg_tmpdir }}/{{ cuda_repo_pkg_name }}"
  when: cuda_repo_check_deb.rc == 1

- name: Install CUDA repository package
  apt: deb="{{ pkg_tmpdir }}/{{ cuda_repo_pkg_name }}"
  when: cuda_repo_check_deb.rc == 1

- name: Install nvidia driver and CUDA
  apt: name={{ item }} state=present update_cache=yes install_recommends=no
  with_items:
    - cuda={{ cuda_version }}*
    - cuda-drivers={{ nvidia_driver_version }}.*
    - nvidia-{{ nvidia_driver_version }}
    - nvidia-{{ nvidia_driver_version }}-dev
    - nvidia-{{ nvidia_driver_version }}-uvm
    - nvidia-settings={{ nvidia_driver_version }}.*
