---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install general dependencies for Caffe
  apt: name={{ item }} state=present update_cache=yes
  with_items: pkg_requirements
  when: ansible_os_family == 'Debian'
